### ISSUE TITLE
record-2021-08-11 12:14:23.600616 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#10]
```yaml
repo: "123"
actor: "123"
links:
    - name: "123"
      url: https://github.com/onsi/ginkgo/issues/711
    - name: "123"
      url: https://github.com/onsi/ginkgo/issues/711
    - name: "123"
      url: https://github.com/onsi/ginkgo/issues/711
    - name: "123"
      url: https://github.com/onsi/ginkgo/issues/711
    - name: "123"
      url: https://github.com/onsi/ginkgo/issues/711
    - name: "123"
      url: https://github.com/onsi/ginkgo/issues/711
message: "123123"
status: ""
starttime: null
endtime: null
```
