### ISSUE TITLE
record-2021-08-12 01:59:44.964193 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#13]
```yaml
repo: ""
actor: ""
links: []
message: ""
status: ""
starttime: 2021-08-12T09:52:08.839614+08:00
endtime: 2021-08-12T09:59:44.964107+08:00
```
