### ISSUE TITLE
record-2021-08-12 04:19:27.355921 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#14]
```yaml
repo: ""
actor: ""
links: []
message: ""
status: ""
starttime: 2021-08-12T12:19:24.771953+08:00
endtime: 2021-08-12T12:19:27.355754+08:00
```
