### ISSUE TITLE
record-2021-08-12 04:20:05.447273 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#15]
```yaml
repo: ""
actor: ""
links: []
message: ""
status: ""
starttime: 2021-08-12T12:20:02.962932+08:00
endtime: 2021-08-12T12:20:05.447119+08:00
```
