### ISSUE TITLE
record-2021-08-12 04:21:31.466831 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#16]
```yaml
repo: ""
actor: ""
links: []
message: ""
status: ""
starttime: 2021-08-12T12:21:27.095445+08:00
endtime: 2021-08-12T12:21:31.466741+08:00
```
