### ISSUE TITLE
record-2021-08-12 04:26:04.270442 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#17]
```yaml
repo: ""
actor: ""
links: []
message: ""
status: ""
starttime: 2021-08-12T12:25:58.370365+08:00
endtime: 2021-08-12T12:26:04.270323+08:00
```
