### ISSUE TITLE
record-2021-08-12 04:50:39.511168 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#18]
```yaml
repo: ""
actor: ""
links: []
message: ""
status: ""
starttime: 2021-08-12T12:40:24.979236+08:00
endtime: 2021-08-12T12:50:39.510979+08:00
```
