### ISSUE TITLE
record-2021-08-11 10:45:10.155886 +0000 UTC

### ISSUE THREAD

**Issue by YanniHu1996** [YanniHu1996/issue-lock-demo#7]
```yaml
repo: "123"
actor: "123"
links: []
message: "123123"
status: ""
starttime: null
endtime: null
```
